services:
  rust:
    build:
      context: ./options_analyzer
    ports: 
      - "50005:50005"
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - ~/.docker-conf/rabbitmq/data:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - rabbitmq_go_net
  timescale:
    container_name: timescale
    image: timescale/timescaledb-ha:pg16-all
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5444:5432
    networks:
      - rabbitmq_go_net
    restart: unless-stopped


networks:
  rabbitmq_go_net:
    driver: bridge
