name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build db + rabbitmq
      run: docker compose build rabbitmq timescale
    - name: run db + rabbitmq for testing
      run: docker compose up rabbitmq timescale -d
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: shutdown containers
      run: docker compose down
