name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_TEST_TIME_UNIT: 60

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build db + rabbitmq
      run: docker compose build rabbitmq timescale
    - name: run db + rabbitmq for testing
      run: docker compose up rabbitmq timescale -d
    - name: Build
      working-directory: ./options_analyzer
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./options_analyzer
      run: cargo test --verbose
    - name: shutdown containers
      run: docker compose down
